apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation-container
          image: przmk/reservation-k8:release-1.0.1
          ports:
            - containerPort: 8080
