apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation-container
          image: przmk/reservation-k8:release-1.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-config-reservation
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m" # 1/4 core
            limits:
              memory: "400Mi"
              cpu: "1000m" # 1 core
